sshuser: ubuntu
version: 7
private_ip: "{{inventory_hostname}}"

# Here are variables related to the Tomcat installation

http_port: 8080
https_port: 8443

# This will configure a default manager-gui user:

admin_username: admin
admin_password: adminsecret

war_bucket: nslrepo
war_names:
    - { war_name: 'nxl#editor##1.44' }
    - { war_name: 'nxl#mapper##1.0017' }
    - { war_name: 'nxl#services##1.0122' }
war_deploy_path: /opt/apache-tomcat-7.0.61/webapps

Rails:
    configuration:
        services_clientside_root_url : "https://{{ elb_dns }}/nxl/services/"
        nsl_services : "https://{{ elb_dns }}/nxl/services/"
        nsl_links : "https://{{ elb_dns }}/nxl/services/"
        services : "https://{{ elb_dns }}/nxl/services/"
        name_services : "https://{{ elb_dns }}/nxl/services/name/bpni/"
        reference_services : "https://{{ elb_dns }}/nxl/services/reference/bpni/"
        api_key : 'd0d1e81d-test-apni-editor'
        ldap_admin_username : "uid=admin,ou=system"
        ldap_admin_password : "secret"
        ldap_base : "ou=people,dc=example,dc=com"
        ldap_host : "localhost"
        ldap_port : 10389
        ldap_user_base : "ou=people,dc=example,dc=com"
        ldap_users : "ou=people,dc=example,dc=com"
        ldap_groups : "ou=groups,dc=example,dc=com"
        mapper_root_url : "https://{{ elb_dns }}/nsl/mapper/"
        tree_editor_url : "https://{{ elb_dns }}/nxl/tree-editor/"
        mapper_shard : "bpni"
        action_mailer:
            delivery_method : ":sendmail"
            perform_deliveries : true
            raise_delivery_errors : true
        relative_url_root : "/nxl/editor"
        environment : "production"
        session_key_tag : "test"


services:
    grails:
        serverURL : "https://{{ elb_dns }}/nxl/services"
    link:
        mapperURL : "https://{{ elb_dns }}/nsl/mapper"
        internalMapperURL : "http://localhost:8080/nsl/mapper"
        editor : "https://{{ elb_dns }}/nxl/editor"

mapper:
    grails:
        serverURL : "https://{{ elb_dns }}/nsl/mapper"
    resolverURL : "https://{{ elb_dns }}/nsl/mapper"
    shards:
        baseURL : "https://{{ elb_dns }}"
